name: avi
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.23+23


environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^6.1.2
  scrollable_clean_calendar: ^1.5.0
  google_fonts: ^6.2.1
  carousel_slider_plus: ^7.1.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  html: ^0.15.0 # Check for the latest version
  url_launcher: ^6.3.2 # Use the latest version
  smooth_page_indicator: ^1.1.0
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.3.0
  file_picker: ^10.2.0
  fluttertoast: ^8.2.8
  encrypt: ^5.0.1
  crypto: ^3.0.2
  flutter_inappwebview: ^6.1.5
  syncfusion_flutter_datepicker: ^30.1.39
  flutter_screenutil: ^5.9.0
  day_picker: ^2.3.0
  cached_network_image: ^3.4.0
  animated_custom_dropdown: ^3.1.1
  flutter_searchable_dropdown: ^2.0.0
  dropdown_search: ^5.0.6
  searchable_paginated_dropdown: ^1.3.0
  open_filex: ^4.6.0
  package_info_plus: ^8.3.0
  cryptography: ^2.7.0
  flutter_riverpod: ^3.0.0
  dropdown_button2: ^2.3.9
  pdf: ^3.11.3
  animated_search_bar: ^2.8.0
  new_version_plus: ^0.1.1
  fl_chart: ^1.1.1
  lottie: ^3.1.2
  syncfusion_flutter_pdfviewer: ^30.2.7










dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    image_path: "assets/app_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png
    - assets/aipay_uat.html
    - assets/aipay_prod.html




